name: flutter_polyline_points
description: A flutter package to get polyline points by either passing the coordinates or google encoded polyline string
version: 1.0.0-nullsafety
homepage: https://github.com/Dammyololade/flutter_polyline_points

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
