name: Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.0'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Analyze code
      run: dart analyze
      
    - name: Run tests
      run: flutter test
        
    - name: Check formatting
      run: dart format --set-exit-if-changed .
      
    - name: Check pub publish
      run: dart pub publish --dry-run